services:
  server:
    build:
      context: .
    volumes:
      - custom:/kutt/custom
    environment:
        DB_CLIENT: mysql2
        DB_HOST: mariadb
        DB_PORT: 3306
        REDIS_ENABLED: true
        REDIS_HOST: redis
        REDIS_PORT: 6379
    ports:
      - 3000:3000
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
  mariadb:
    image: mariadb:10
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysql ${DB_NAME} --user=${DB_USER} --password=${DB_PASSWORD} --execute "SELECT 1;"']
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db_data_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
      
########### Monitoring Stack ###########
  prometheus:   
    image: prom/prometheus:latest    
    
    container_name: prometheus       
    
    ports:
      - "9090:9090"  
    
    volumes:   # Mount local prometheus.yml into the container 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
 
    restart: unless-stopped  # Auto-restart Prometheus if it crashes

  grafana:       # Service name (Grafana)
    
    image: grafana/grafana:latest    
    
    container_name: grafana          
    
    ports:
      - "4000:3000"   
    
    volumes:
      - grafana-storage:/var/lib/grafana  # Use a named volume to persist Grafana data (dashboards, users, settings)
        
    restart: unless-stopped
    depends_on:
      - prometheus   # Ensure Grafana starts after Prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
    - "--docker_only=true"

    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro # Mount root filesystem as read-only to monitor system stats
      - /var/run:/var/run:ro # Mount Docker runtime to see running containers
      - /sys:/sys:ro         # Mount sys filesystem as read-only for system information
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  db_data_mariadb:
  custom:
  grafana-storage: