version: "3.9"

services:
  server:
    build:
      context: .
    container_name: kutt_app
    restart: always
    environment:
      # --- DATABASE CONFIG ---
      DB_CLIENT: mysql2
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: kutt
      DB_USER: root
      DB_PASSWORD: db_pass
      DB_SSL: "false"
      DB_SSL_REJECT_UNAUTHORIZED: "false"

      # --- REDIS CONFIG ---
      REDIS_ENABLED: "true"
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # --- OTHER OPTIONS ---
      NODE_ENV: production
      PORT: 3000
      SITE_NAME: Kutt
      DEFAULT_DOMAIN: 13.38.61.104:3000
      JWT_SECRET: Depi_final_project
      CUSTOM_DOMAIN_USE_HTTPS: "false"
      TRUST_PROXY: "false"

    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - custom:/kutt/custom

  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: db_pass
      MARIADB_DATABASE: kutt
      # No need to redefine MARIADB_USER=root — it’s implied for root
    volumes:
      - db_data_mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -pdb_pass | grep 'mysqld is alive'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  ########### Monitoring Stack ###########
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - "--docker_only=true"
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  db_data_mariadb:
  custom:
  grafana-storage:
